### ISSUE TITLE
OpenMP offload build fails with undefined `camp::resources::Omp`

### ISSUE THREAD

**Issue by abbotts** [LLNL/RAJA#1111]
I'm not able to get the current develop (81d6990ddb20719ff1a18f723b3bf767b134658b) or the v0.14.0 tag to build with CCE OpenMP offload due to build time failures that seem to originate from CAMP not respecting -DENABLE_TARGET_OPENMP.

I configure with:
```
cmake -DENABLE_OPENMP=On -DENABLE_TARGET_OPENMP=On \
-DENABLE_CUDA=Off -DENABLE_CLANG_CUDA=Off -DENABLE_HIP=Off \
-DENABLE_CLANG_HIP=Off -DENABLE_TBB=Off \
-DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=cc \
-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 \
-DENABLE_TESTS=On -DENABLE_EXAMPLES=Off  ../
```

And get failures looking like:
```
[  2%] Building CXX object test/integration/plugin/CMakeFiles/test-plugin-forall-OpenMP.exe.dir/test-plugin-forall-OpenMP.cpp.o
cd /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/build/test/integration/plugin && /opt/cray/pe/craype/2.7.10.1/bin/CC  -DGTEST_HAS_DEATH_TEST=1 -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/test/include -isystem /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/include -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/test/integration/plugin/tests -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/build/include -I/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/tpl/camp/include  -Wall -Wextra  -O2 -DNDEBUG -fPIE   -fopenmp -std=c++14 -o CMakeFiles/test-plugin-forall-OpenMP.exe.dir/test-plugin-forall-OpenMP.cpp.o -c /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/build/test/integration/plugin/test-plugin-forall-OpenMP.cpp
In file included from /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/build/test/integration/plugin/test-plugin-forall-OpenMP.cpp:11:
In file included from /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/test/include/RAJA_test-base.hpp:15:
In file included from /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include/RAJA/RAJA.hpp:44:
In file included from /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include/RAJA/pattern/forall.hpp:64:
In file included from /home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include/RAJA/policy/MultiPolicy.hpp:31:
/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include/RAJA/util/resource.hpp:112:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/nightly_crons/raja-hip-gfx908/RAJA/include/RAJA/util/resource.hpp:117:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
```

I ran a bisect and the first broken commit was afa2caf49fbdf25359320c6609dee1a1e47912f4 , but since that was reverted when CAMP was updated it is probably a regression in CAMP. Just quickly looking at CAMP my initial guess is that it's missing a cmake define in the config file or something. I'll try to identify the actual error in camp and open an issue or PR there. Another, less likely, option might be the `-DENABLE_TARGET_OPENMP=On` option not propagating to CAMP.

**Comment by rchen20** [comment]
Hi @abbotts, we've made some updates in the Camp repo which should solve this problem (https://github.com/LLNL/camp). If you have a chance, would you mind trying camp/main to see if this fixes your issue? Thanks!

**Comment by rhornung67** [comment]
I  think Tom said the fix was in camp develop??

**Comment by rchen20** [comment]
Tom did say develop, but he actually meant "main". 🙂

**Comment by abbotts** [comment]
This got lost in a flood of emails. I'm trying to test now with current RAJA/develop and camp/main, but a stray `-ltarget_openmp` has made it onto the link line for some reason and I can't progress far enough to build the test.

I'll need to track that down and figure out how to get rid of it before I can test the CAMP changes. I may not have time for that until next week.

**Comment by rhornung67** [comment]
@abbotts is this (and the following 'foreach' logic) the root of the issue you are seeing? https://github.com/LLNL/camp/blob/main/CMakeLists.txt#L52

@trws thoughts?

**Comment by trws** [comment]
That's interesting, it's the right target for camp to be using, and should behave with BLT downstream, but I'm not sure what we should do for non-BLT consumers.  They do need to include OpenMP offload support for some of the headers to work, but since that target is BLT specific... Will have to chat this over I think and make sure camp and RAJA match up on the behavior.

**Comment by davidbeckingsale** [comment]
BLT doesn't provide that target - we handle OpenMP offload by depending on `openmp` and explicitly putting the offload flags in OpenMP_CXX_FLAGS (e.g. https://github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_clang_omptarget.sh#L42)

**Comment by trws** [comment]
I think this ends up being addressed with the exported target fixes we were working on, should probably check if RAJA develop/camp main has this working, it should.

**Comment by abbotts** [comment]
No luck with RAJA develop on an internal HPE system using the configure command I opened the ticket with. Still getting:

```
Scanning dependencies of target test-plugin-workgroup-Sequential.exe
[  3%] Building CXX object test/integration/plugin/CMakeFiles/test-plugin-workgroup-Sequential.exe.dir/test-plugin-workgroup-Sequential.cpp.o
In file included from /home/users/sabbott/git/RAJA/cce_build/test/integration/plugin/test-plugin-workgroup-Sequential.cpp:11:
In file included from /home/users/sabbott/git/RAJA/test/include/RAJA_test-base.hpp:15:
In file included from /home/users/sabbott/git/RAJA/include/RAJA/RAJA.hpp:44:
In file included from /home/users/sabbott/git/RAJA/include/RAJA/pattern/forall.hpp:64:
In file included from /home/users/sabbott/git/RAJA/include/RAJA/policy/MultiPolicy.hpp:31:
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:119:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:124:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:129:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:134:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:139:35: error: no type named 'Omp' in namespace 'camp::resources'
    using type = camp::resources::Omp;
                 ~~~~~~~~~~~~~~~~~^
/home/users/sabbott/git/RAJA/include/RAJA/util/resource.hpp:159:47: error: no member named 'Omp' in namespace 'RAJA::resources'
    template <> struct is_resource<resources::Omp> : std::true_type {};
```

```
~/git/RAJA/cce_build> git rev-parse --short HEAD
0f96dd476
```

I can go hop over to camp main and check there as well.

**Comment by davidbeckingsale** [comment]
@abbotts did you try manually setting the OpenMP offload flags, as done here: https://github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_clang_omptarget.sh#L42

**Comment by abbotts** [comment]
Hmmm.. okay, this works:

```
cmake -DENABLE_OPENMP=On -DENABLE_TARGET_OPENMP=On -DRAJA_ENABLE_OPENMP=On -DRAJA_ENABLE_TARGET_OPENMP=On -DENABLE_CUDA=Off -DENABLE_CLANG_CUDA=Off -DENABLE_HIP=Off  -DENABLE_TBB=Off -DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=cc -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -DENABLE_TESTS=On -DENABLE_EXAMPLES=Off  ../
```

If it's intended that CMake options are `RAJA_` prefaced, then we can close this. 

(And I'll open another bug, because not specifying -DENABLE_OPENMP=On` gives:
```
CMake Error at cmake/SetupDependentOptions.cmake:19 (message):
  RAJA_ENABLE_OPENMP set to On, but ENABLE_OPENMP is Off.  Please set
  ENABLE_OPENMP to On enable this feature.
Call Stack (most recent call first):
  CMakeLists.txt:110 (include)


-- Configuring incomplete, errors occurred!
See also "/home/users/sabbott/git/RAJA/cce_build/CMakeFiles/CMakeOutput.log".
```
)

**Comment by rhornung67** [comment]
@abbotts a few comments:

1. RAJA_ENABLE_OPENMP should not be needed if ENABLE_OPENMP is on. RAJA_ENABLE_OPENMP is a CMake dependent option and so typically would be used to enable OpenMP in a build, but turn it off in RAJA by setting RAJA_ENABLE_OPENMP to off
2. RAJA_ENABLE_TARGET_OPENMP is not a dependent option in RAJA, and is specific to RAJA, since it's not supported in BLT and not in CMake (I think)
3. You shouldn't need to explicitly turn off CUDA, CLANG_CUDA, HIP, and TBB, since they are off by default in RAJA.

@davidbeckingsale these statements are correct, right?

**Comment by abbotts** [comment]
Okay @rhornung67 , that makes sense and I see it in the documentation, although I still think it would be nice to purge https://github.com/LLNL/RAJA/blob/0f96dd4761ee4dcd98ec72660ad0046f9970cf0c/cmake/SetupRajaConfig.cmake#L59 so `ENABLE_TARGET_OPENMP` doesn't get used and you get a proper warning:

```
  Manually-specified variables were not used by the project:

    ENABLE_TARGET_OPENMP

```

(3) are all off by default. Just a copy-paste from the output of a more generic testing script.

**Comment by abbotts** [comment]
Closing since this works now when configured with `RAJA_ENABLE_TARGET_OPENMP`, which is the documented option.
